### PR TITLE
Update from first round.

### PR DESCRIPTION
**Pull request by cnlohr**
* Move Microphone
* Switch microphone for new mic.
* Switch support circuitry for new mic.
* Deleted extra screw.
* Moved components on back in so that none are within 1mm of the edge.
* Tweaked power for gyro.
* Removed rumble drive circuitry.
* Tweaked footprint on magnetometer.

Additional: Shrunk touch pad, it is now 24.5mm across.
Additional: Not sure why pinout on touchpad appeared different on updated touch pad - this should make them the same.

See #11

### CODE REVIEW

**Comment by AEFeinstein** [comment]
I wish I could disable branches altogether for this repo. It's not like we can cleanly merge kicad files. When you're done with your last task, per #11 "Pending, remove unused circuitry" let me know and I'll double check the changes and apply the silkscreen art

**Comment by AEFeinstein** [comment]
Also don't forget to run DRC! I see an overlapping part
image
And a few vias too close to traces
image
image
image
Also it whines a lot about the tiny magnetometer, but the solution there may be to update DRC rules for that part.

**Comment by AEFeinstein** [comment]
There are also a handful of warnings about dangling traces and vias to nowhere. If you don't clean those up, I will, because I am a DRC nut.

**Comment by AEFeinstein** [comment]
Also the touchpad is _slightly_ off-center and the LED D9 can be moved up to the touchpad's edge. These are trivial to adjust, so if you want I can do that when yo urelease the mutex
image

**Comment by cnlohr** [comment]
Ok, updated with changes here.  Merging.

**Pull request merged**
